Fixed "TypeError columns.split is not a function"
Added a conditional check to detect if "columns" is already an array, then there's no needs to split it into an array again.